### PR TITLE
Adapt to tidyr v1.0.0

### LINKED ISSUE #195: group.by gives error: Column p must be length 1 (the group size)
Running
```
require(ggpubr)
data("ToothGrowth")
df <- ToothGrowth
compare_means(len ~ supp, df, group.by = "dose")
```

gives the following error message: `Error: Column `p` must be length 1 (the group size), not 3`.

```
> version
 
platform       x86_64-apple-darwin15.6.0                  
arch           x86_64                                     
os             darwin15.6.0                               
system         x86_64, darwin15.6.0                       
status         Patched                                    
major          3                                          
minor          5.3                                        
year           2019                                       
month          03                                         
day            11                                         
svn rev        76864                                      
language       R                                          
version.string R version 3.5.3 Patched (2019-03-11 r76864)
nickname       Great Truth  


> packageVersion("ggpubr")
[1] ‘0.2.1.999’
```

### PR DESCRIPTION
**Pull request by jennybc**
Closes #195

As mentioned in #195, the root issue here is that `tidyr::nest()` now returns a grouped object, which has implications for downstream manipulations via, e.g., dplyr.

### CODE REVIEW

File: R/compare_means.R [hunk 1]
```diff
@@ -193,9 +193,12 @@ compare_means <- function(formula, data, method = "wilcox.test",
...
     grouped.d <- .group_by(data, group.by)
-    pvalues <- purrr::map(grouped.d$data, test.func, formula = formula,
-                          method = method, paired = paired, p.adjust.method = "none",...)
-    res <- grouped.d %>% mutate(p = pvalues) %>%
+    res <- grouped.d %>%
+      mutate(p = purrr::map(
+        data,
+        test.func, formula = formula,
+        method = method, paired = paired, p.adjust.method = "none",...)
+      ) %>%
```
Comment (jennybc) [inline R/compare_means.R]: Doing this `map()` inside the `mutate()`, instead of outside, makes this code work for current and dev versions of tidyr.

File: R/compare_means.R [hunk 2]
```diff
@@ -233,6 +236,7 @@ compare_means <- function(formula, data, method = "wilcox.test",
   by_y <- res %>% group_by(.y.)
   pvalue.adj <- do(by_y, .p.adjust(., method = p.adjust.method))
   res <- res %>%
+    dplyr::ungroup() %>%
```
Comment (jennybc) [inline R/compare_means.R]: An explicit `ungroup()` here makes the code work for CRAN and dev versions of tidyr.

**Comment by kassambara** [comment]
Thank you @jennybc for this contribution, highly appreciated!

**Comment by jennybc** [comment]
Great! So can you do a small release of ggpubr, in the near future?

**Comment by kassambara** [comment]
ggpubr is submitted now to CRAN

**Comment by jennybc** [comment]
Excellent! Thanks for doing attending to this in such a timely manner.

**Comment by kassambara** [comment]
You are welcome
